site_name: iOS Developer Guide
site_url: 'http://developer.jwplayer.com/sdk/ios/docs/developer-guide/'
site_favicon: favicon.png
docs_dir: docs
site_dir: developer-guide
theme:
  name: null
  custom_dir: ../node_modules/mkdocs-jwplayer/jwplayer
  include_search_page: true
  search_index_only: false

markdown_extensions:
   - markdown_fenced_code_tabs
extra:
  singlePage: true
  noindex: true
  product: android
nav:
- Getting Started:
  - 'Introduction': 'index.md'
