site_name: Android Developer Guide
site_url: 'http://developer.jwplayer.com/sdk/android/docs/developer-guide/'
site_favicon: favicon.png
docs_dir: docs
site_dir: developer-guide
theme:
  name: null
  custom_dir: ../node_modules/mkdocs-jwplayer/jwplayer
  include_search_page: true
  search_index_only: false
extra:
  noindex: true
  product: android
nav:
- Getting Started:
  - 'Introduction': 'index.md'
  - 'Download the SDK': 'getting-started/download-the-sdk.md'
  - 'Configure ProGuard': 'getting-started/configure-proguard.md'
  - 'Configure the manifest': 'getting-started/configure-the-manifest.md'
  - 'Add a player to an activity': 'getting-started/add-a-player-to-an-activity.md'
- Content:
  - 'Playlists': 'interaction/playlists.md'
  - 'Captions API': 'interaction/captions.md'
  - 'Playing secure content': 'drm/drm-protected-playback.md'
  - 'Custom HTTP headers': 'drm/custom-http-headers.md'
- Branding:
  - 'XML Options and PlayerConfig': 'customization/xml-options-and-playerconfig.md'
  - 'CSS Skins': 'customization/css-skins.md'
  - 'Localization': 'customization/localization.md'
- Behavior:
  - 'ExoPlayer API': 'interaction/exoplayer.md'
  - 'Playback API': 'interaction/playback.md'
  - 'Quality API': 'interaction/quality.md'
  - 'Audio API': 'interaction/audio.md'
  - 'Related Feed API' : 'interaction/related.md'
  - 'Multi-Window Mode': 'interaction/multiwindow.md'
  - 'Enable casting to Chromecast devices': 'chromecast/enable-casting-to-chromecast-devices.md'
  - 'Customization': 'chromecast/customization.md'
- Advertising:
  - 'Advertising Overview': 'advertising/overview.md'
  - 'VAST': 'advertising/vast.md'
  - 'Google IMA': 'advertising/google-ima.md'
  - 'FreeWheel': 'advertising/freewheel.md'
  - 'Advertising API': 'interaction/advertising.md'
- Analytics:
  - 'Analytics': 'integration/analytics.md'
- Troubleshooting:
  - 'Create an Android reproduction app': 'troubleshooting/create-an-android-reproduction-app.md'
- Reference:
  - 'JavaDocs': 'interaction/javadocs.md'
- Migration Guides:
  - 'Migration from v1.x to v2.x (Nov 17 2015)': 'migration/v2.md'
  - 'Migration from v2.7 to v2.8 (Feb 22 2018)': 'migration/v2-8.md'
  - 'Migration from v2.x to v3.x': 'migration/v3.md'
- About:
  - 'License': 'about/license.md'
  - 'Release Notes': 'about/release-notes.md'
  - 'System Requirements': 'about/requirements.md'
