site_name: Android Developer Guide
site_url: 'http://developer.jwplayer.com/sdk/android/docs/developer-guide/'
site_favicon: favicon.png
docs_dir: docs
site_dir: developer-guide
theme:
  name: null
  custom_dir: ../node_modules/mkdocs-jwplayer/jwplayer
  include_search_page: true
  search_index_only: false
extra:
  noindex: true
  product: android
pages:
- Welcome:
  - 'Introduction': 'index.md'
  - '3.x Documentation': '3x-redirect.md'
- Getting Started:
  - 'Library and Project Setup': 'getting-started/library-project-setup.md'
- Creating a JWPlayer:
  - 'JWPlayerFragment': 'usage/jwplayer-fragment.md'
  - 'JWPlayerView': 'usage/jwplayer-view.md'
- Advertising:
  - 'Advertising Overview': 'advertising/overview.md'
  - 'VAST': 'advertising/vast.md'
  - 'Google IMA': 'advertising/google-ima.md'
  - 'FreeWheel': 'advertising/freewheel.md'
- Interacting with the JW Player:
  - 'Playback API': 'interaction/playback.md'
  - 'Playlists': 'interaction/playlists.md'
  - 'Quality API': 'interaction/quality.md'
  - 'Audio API': 'interaction/audio.md'
  - 'Captions API': 'interaction/captions.md'
  - 'Related Feed API' : 'interaction/related.md'
  - 'JavaDocs': 'interaction/javadocs.md'
- Customization:
  - 'XML Options and PlayerConfig': 'customization/xml-options-and-playerconfig.md'
  - 'CSS Skins': 'customization/css-skins.md'
  - 'Localization': 'customization/localization.md'
- Digital Rights Management:
  - 'Playing secure content': 'drm/drm-protected-playback.md'
  - 'Custom HTTP headers': 'drm/custom-http-headers.md'
- Chromecast:
  - 'Getting started': 'chromecast/getting-started.md'
  - 'Customization': 'chromecast/customization.md'
  - 'Supported Media': 'chromecast/supported-media.md'
  - 'Known issues': 'chromecast/known-issues.md'
- Migration Guides:
  - 'Migration from v1.x to v2.x (Nov 17 2015)': 'migration/v2.md'
  - 'Migration from v2.7 to v2.8 (Feb 22 2018)': 'migration/v2-8.md'
- About:
  - 'License': 'about/license.md'
  - 'Release Notes': 'about/release-notes.md'
  - 'System Requirements': 'about/requirements.md'
