site_name: iOS Developer Guide
site_url: 'http://developer.jwplayer.com/sdk/ios/docs/developer-guide/'
site_favicon: favicon.png
docs_dir: docs
site_dir: developer-guide
theme:
  name: null
  custom_dir: ../node_modules/mkdocs-jwplayer/jwplayer
  include_search_page: true
  search_index_only: false

markdown_extensions:
   - markdown_fenced_code_tabs
extra:
  noindex: true
  product: ios
nav:
- Getting Started:
  - 'Introduction': 'index.md'
  - 'Download the SDK': 'getting-started/download-the-sdk.md'
  - 'Configure your project': 'getting-started/configure-your-project.md'
  - 'Add a player to your app': 'getting-started/add-a-player-to-your-app.md'
  - 'Basic Embedding': 'embedding/embedding.md'
- Content:
  - 'Captions': 'customization/captions.md'
- Branding:
  - 'Custom Skins': 'customization/building-skins.md'
- Behavior:
  - 'Advanced Features': 'embedding/features.md'
  - 'Callbacks': 'api/callbacks.md'
  - 'AirPlay': 'casting/airplay.md'
  - 'Chromecast': 'casting/chromecast.md'
- Advertising:
  - 'Basic Ad Embed': 'monetization/ad-configuration.md'
  - 'Ad Scheduling': 'monetization/ad-schedules.md'
  - 'Tag Waterfall': 'monetization/ad-waterfall.md'
  - 'Ad tag variables': 'monetization/ad-tag-variables.md'
  - 'Non linear ads': 'monetization/nonlinear-ads.md'
  - 'Google IMA': 'monetization/ad-google_ima.md'
  - 'FreeWheel': 'monetization/freewheel.md'
  - 'Ad Rules': 'monetization/ad-rules.md'
- Analytics:
  - 'Analytics': 'integration/analytics.md'
- Troubleshooting:
  - 'Q&A' : 'troubleshooting/troubleshooting.md'
  - 'Create an iOS reproduction app': 'troubleshooting/create-an-ios-reproduction-app.md'
- Reference:
  - 'Classes': 'api/classes.md'
- Migration:
  - 'To 3.x from 2.x': 'migration/v3.md'
  - 'To 2.8.0 from 2.7.x': 'migration/v2dot8.md'
- About:
  - 'License': 'about/license.md'
  - 'Release Notes': 'about/release-notes.md'
